listen-address = ":8080"

# refresh to get latest hosts 
refresh-interval-second=3600

# how many workers to check host ssl certs
concurrency=5


[[hosts]]
    address = "www.supertechfans.com"
    alert-emails = ["supertechfans@gmail.com", "rmrf@qq.com"]
[[hosts]]
    address = "baidu.com:443"
    alert-emails = ["rmrf@qq.com"]
