version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  ssl-certs-check:
    build:
      context: .
      args:
        - ENV_GOPROXY=https://goproxy.cn,direct
    image: local/ssl-certs-check
    container_name: ssl-certs-check
    volumes:
      - ./config.toml:/app/config.toml
    command:
      - '-config=/app/config.toml'
    ports:
      - 8080:8080

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./configurations/alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./configurations/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configurations/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./configurations/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./configurations/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
