version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  ssl-certs-check:
    build:
      context: .
      args:
        - ENV_GOPROXY=https://goproxy.cn,direct
    image: local/ssl-certs-check
    container_name: ssl-certs-check
    volumes:
      - ./configurations:/app/configurations
    command:
      - '-config=/app/configurations/config.toml'
    ports:
      - 8080:8080

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./configurations/alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093
    depends_on:
      - ssl-certs-check

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./configurations/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configurations/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    depends_on:
      - ssl-certs-check

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./configurations/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./configurations/grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/all.yaml
      - ./configurations/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
      - ./configurations/grafana_dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - ssl-certs-check