listen-address = ":8080"

# refresh to get latest hosts 
refresh-interval-second=3600

# how many workers to check host ssl certs
concurrency=5


[[hosts]]
    address = "www.supertechfans.com"
    alert-emails = ["u1@example.com", "u2@example.com"]
[[hosts]]
    address = "githube.com:443"
    alert-emails = ["abc@example.com"]
